version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wwe-superstars"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1oi6cfbv4ehkr"
s3_prefix = "wwe-superstars"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

